remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Maker Badges
description: Physical maker badges to vinyl cut, 3D print, and share — celebrate your maker skills!
show_downloads: false
google_analytics: G-C3T6SZRDCV
