remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Maker Badges
description: A page for storing various badges for makers
show_downloads: false
google_analytics: G-C3T6SZRDCV
